import '../styles/globals.css'
import Layout from '../components/Layout'
import Head from 'next/head'



function MyApp({ Component, pageProps}) {
  return (

  <>
      <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/app-fav.png" />
      </Head>
       
    </div>
  <Layout>
<Component {...pageProps} />
  </Layout>
  
  </>

  )
}

export default MyApp
