import Head from 'next/head'
import Box from '@mui/material/Box';



export default function Home() {
  return (
    <Box>
      <Head>
        <title>Whats app web is her</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/app-fav.png" />
      </Head>
   
    </Box>
  )
}
